modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="fnafsotmmod"
version="0.01.0"
displayName="Five Nights at Freddy's: The Secret of the Mimic Mod"
displayURL="https://curseforge.com"
logoFile="logo.png"
credits="Five Nights at Freddy's: The Secret of the Mimic by Steel Wool Studio & ScottGames"
authors="SonovArcoc"
description="This is Five Nights at Freddy's: The Secret of the Mimic Mod"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.fnafsotmmod]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.137,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.fnafsotmmod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration